Added TV-Shows section
mstuttgart/awesome-time-travel pull request #9
Opened 2017-10-23 23:35 UTC by iMoose

2017-10-23 23:38 UTC, mstuttgart commented
HI @iMoose thanks to you PR. Please rebase you branch to the latest commit.

Let me know if you need help.

2017-10-23 23:43 UTC, iMoose commented
Conflict resolved

2017-10-24 00:10 UTC, mstuttgart requested changes
Thanks to resolve the conflict, but the README file is wrong. 

The `book` section is in the wrong place, I believe than rebase is wrong.

2017-10-24 00:13 UTC, mstuttgart commented
You can rebase you repo like the:

```
git remote add upstream git@github.com:mstuttgart/awesome-time-travel.git
git fetch upstream
git pull --rebase upstream master
``` 
Fix the conflicts add tip:

```
git add .
git rebase --continue
git push -f origin patch-2
```

2017-10-24 01:11 UTC, mstuttgart requested changes

2017-10-24 01:11 UTC, mstuttgart commented on README.md
> -* [11/22/63](https://en.wikipedia.org/wiki/11/22/63) - Stephen King - 2011
@iMoose this movie was removed. Please fix this

2017-10-24 01:32 UTC, mstuttgart commented
@iMoose thanks for this PR, but the `TV-show` section already added.

2017-10-24 01:32 UTC, closed without merging